### ISSUE TITLE
Dropdowns in Google Docs not supported

### ISSUE THREAD

**Issue by jnsgruk** [canonical/specs-v1.canonical.com#110]
Hi

In a move to try and make the spec template a little easier to use, I created a [dropdown](https://www.howtogeek.com/803342/create-a-drop-down-list-in-google-docs/) in the table, hoping it would help standardise the terms people use.

Unfortunately, that seems incompatible with the current automation that scrapes the specs:

E.g.

![image](https://user-images.githubusercontent.com/668505/205106654-46255d7a-bd3f-4e46-afaa-a2268f9a90d0.png)

From the spec: https://docs.google.com/document/d/1BYyMZhvUjl7KyBwzmjnk7RI_NmVAlMIz5HrQoLMubn8/edit

Thanks!
Jon

**Comment by jnsgruk** [comment]
Interestingly, if I click on the spec, it can pick up that it's approved: 

![image](https://user-images.githubusercontent.com/668505/205107106-f3730eff-ee70-4013-bd91-8206e9f1577b.png)

**Comment by anthonydillon** [comment]
I have dug down into the good script which populates the spreadsheet that acts as the source for this site. I believe it would be a typeof condition to either pull the value from the tag or the raw string.
