### ISSUE TITLE
Metadata table parsing seems to break with comments

### ISSUE THREAD

**Issue by jnsgruk** [canonical/specs-v1.canonical.com#122]
Looking at the following picture:

![image](https://user-images.githubusercontent.com/668505/211788835-aa54a737-889b-4128-aae1-ba3efc477e42.png)

It seems that the spec index number "PR006" isn't picked up correctly. If I look at that first doc, the only difference between it and others where the index is parsed correctly, is that there is a comment on the index number, which looks to be messing with the parsing -- you can see that more in the expanded view:

![image](https://user-images.githubusercontent.com/668505/211789182-98480617-974f-4a78-b7a0-51ed80f194cc.png)

**Comment by anthonydillon** [comment]
This seems to have been resolved in the updater cron. I can no longer replicate this.
