### ISSUE TITLE
If there is no spec file the build crashes

### ISSUE THREAD

**Issue by anthonydillon** [canonical/specs-v1.canonical.com#145]
https://github.com/canonical/specs.canonical.com/blob/d2c48a22a60008432bc6c6bb762c73fe10a9418f/webapp/app.py#L29-L47

If you have no `specs.json` file we skip the initialisation of `all_specs` which crashes when you try and `copy.deepcopy(all_specs)` in the homepage route.

**Comment by andesol** [comment]
You mean when running the project locally? See #146
