### ISSUE TITLE
Specs are out of sync with google drive

### ISSUE THREAD

**Issue by ghislainbourgeois** [canonical/specs-v1.canonical.com#173]
The specs are out of sync with the content of google drive for the Telco team. More specifically, the status of the specs do not seem to be properly updated anymore. 

An example of this is the spec TE068, that has been approved for at least 2 weeks and is still being shown as Pending Review on the website.

Other specs that should be Pending Reviews are not being shown at the moment. It is making it difficult to find what needs my reviews currently.

Please let me know if more data is required for this issue.

**Comment by andesol** [comment]
The script that updates the specs got stuck. I've checked `TE068` and it's showing as approved now, so I think it works again. 

Thanks for reporting @ghislainbourgeois!
