### ISSUE TITLE
Only last 100 specs visible for each folder

### ISSUE THREAD

**Issue by jurekh** [canonical/specs-v1.canonical.com#176]
It appears that the data source spreadsheet does not contain all the specs - only a hundred most recent ones are listed in the spreadsheet. 

I think that's because the [get_files()](https://github.com/canonical/specs.canonical.com/blob/6f0436f4d893851d9ee4d5e126d73a325a799717/webapp/google.py#L59) method tries to use `nextPageToken`. [Google API doc](https://github.com/googleapis/google-api-python-client/blob/main/docs/pagination.md) mentions that for retrieving multiple pages of results, one should use `list_next()`.

**Comment by benhoyt** [comment]
Probably related to this, it seems a whole bunch of specs and teams are now missing from specs.canonical.com (for example, I don't see our OPnnn specs there, nor STnnn specs).
