### ISSUE TITLE
Add H1 on page

### ISSUE THREAD

**Issue by tbille** [canonical/specs-v1.canonical.com#45]
Let's add an H1 a bit descriptive of what people or watching in the homepage

**Comment by tbille** [comment]
For @marinacastejon to propose a title.

**Comment by marinacastejon** [comment]
@goulinkh I'd go with the simplest option: "Canonical Specifications"

Other options: 
- Team Specifications
- Engineering Specifications
- Specifications library
- Specifications finder

**Comment by goulinkh** [comment]
Thanks @marinacastejon I think "Canonical Specifications" is great!
