### ISSUE TITLE
Usernames autocompleted as contact address are not displayed

### ISSUE THREAD

**Issue by jibel** [canonical/specs-v1.canonical.com#61]
In google doc, people names are auto-completed as email addresses links when the contact is in address book of the user.
For example in [WS005](https://docs.google.com/document/d/1cZ_p7ZegU1mmD0B-KHaN0AL7y1-nsU48Dz_CGyDR9o0/edit), "_Didier Roche_" is actually _[Didier Roche](mailto:didier.roche@canonical.com)_

These names are not parsed correctly and not listed on specs.c.c. In the case of WS005 the only author visible is "_Jean-Baptiste Lallement,_" while is should be "_Jean-Baptiste Lallement, Didier Roche, Patrick Wu,  Sohini Roy_"

Of course the original spec can be fixed by replacing the email address link by a non link text. But Google Doc is pretty stubborn sometimes trying to help users and that's lot of manipulation to enter a name without a link and easy to forget to do so.

Could specs.c.c strip the links from the "Author" field and keep only the text of the link in order to correctly display them on the frontend?

**Comment by goulinkh** [comment]
Thanks @jibel for your feedback, we will fix this as soon as possible!

@tbille there is an issue in the export script on this [spreadsheet](https://docs.google.com/spreadsheets/d/1jFj4z19cXZaPZcZk8nPTPmeO0zBbja5Bg23eXiZr9Pw/edit#gid=0) where we are missing some authors for the spec index `WS005`
