### ISSUE TITLE
Chips should be interactive

### ISSUE THREAD

**Issue by clagom** [canonical/specs-v1.canonical.com#65]
According to the spec for our chip component (see https://docs.google.com/document/d/1gAq0oliQ5XEPuwJs8IUrdZNBKFuEWjSyLDuGeC4oSNw/edit#), chips should always be interactive (otherwise we use another component instead).
@AnnSoMuller and @rayito please consider whether we want to add a "click + filter" functionality to the chips, or if we want to use a non-interactive status-label insteac. CC @danielmutis

**Comment by AnnSoMuller** [comment]
Yes, That was the plan to have the click and filter behaviour that goes with the chip component :)

**Comment by clagom** [comment]
Can we then make this an issue for dev to implement that behaviour @AnnSoMuller thanks

**Comment by rayito** [comment]
The site already has a set of checkboxes to filter by Status:

![image](https://user-images.githubusercontent.com/5860630/168794810-27f2eea5-bf22-42d8-8064-133b73defa4f.png)

I don't know if we should use a component inside the cards to filter by that as well. It feels a bit arbitrary, we show Status, Team, Type and Author in the card, but we only allow users to filter the Status from the card. 

I might be missing some context, but I think in this case all the info inside the card could be static and use only the filters on the left side of the site (and therefore changing the chips for labels).

**Comment by danielmutis** [comment]
I agree with Eden, I think this should be labels instead of chips. I don't see how the filtering from the cards would work (i.e. would it tick a checkbox on the left? I think it'd be a messy interaction).

**Comment by marinacastejon** [comment]
I agree with comments above. I think it will also simplify things if there is only one interaction in the card (showing that spec doc).
Keep in mind as well that for the filters on the left hand-side, I had already included teams and authors as 2 fields to be switched to the enhanced version of the multi-select (as discussed in a previous DA). This will make using filters more efficient.
[Miro board](https://miro.com/app/board/uXjVO768S1A=/?share_link_id=772577848981):
![image.png](https://images.zenhubusercontent.com/61309e789df65d8124887eac/b7f12154-50b7-44d8-8c56-45779c7234e4)

**Comment by AnnSoMuller** [comment]
ok, sure. :) So let make them Status labels then. It is also fine to iterate if needed.

**Comment by andesol** [comment]
We'll use status labels then :+1: --> #71
