### ISSUE TITLE
Sort order doesn't seem to be preserved

### ISSUE THREAD

**Issue by bartaz** [canonical/specs-v1.canonical.com#75]
### How to reproduce:

- Go to any spec listing, for example Web&Design: https://specs.canonical.com/?query=&team=WD+-+Web+%26+Design
- Choose sorting other then last modified (for example by spec index)
- Click on any spec to open it (in same tab)
- Go back from spec to spec listing

### Expected

Chosen sort order should be preserved.

### What happens

Even though sort dropdown shows "Spec index" the actual sorting is default (last modified date).

**Comment by sparkiegeek** [comment]
Doesn't happen anymore
