### ISSUE TITLE
Shared links do not update filters

### ISSUE THREAD

**Issue by elioqoshi** [canonical/specs-v1.canonical.com#77]
When filtering the URL of the page gets updated according to the filter:
<img width="1333" alt="grafik" src="https://user-images.githubusercontent.com/5436686/170262562-85f5ef64-896f-4541-b6da-e0d28872d28b.png">

visiting the same link however loses the filtering and all specs are shown

<img width="1314" alt="grafik" src="https://user-images.githubusercontent.com/5436686/170262742-900d3b3e-ae4f-4fc6-a65c-90fb3b17ee93.png">

**Comment by bartaz** [comment]
May be related to https://github.com/canonical-web-and-design/specs.canonical.com/issues/75

**Comment by sparkiegeek** [comment]
Doesn't happen any more, URL format has changed
