### ISSUE TITLE
Pending Review missing from App.tsx const

### ISSUE THREAD

**Issue by j5awry** [canonical/specs-v1.canonical.com#87]
From the [internal canonical spec](https://docs.google.com/document/d/1lStJjBGW7lyojgBhxGLUNnliUocYWjAZ1VEbbVduX54/edit#heading=h.bluiswde0s4) the workflow is:

starts: Braindump -> Drafting

pending: `Withdrawn <---Pending Review---> Pending Approval`
 final review: `Rejected     Approved`
implementation: `Active    Completed`

`Obsolete`

The const list at https://github.com/canonical/specs.canonical.com/blob/main/client/App.tsx#L10   is missing Pending Review, leading to some things falling into "Unknown"

**Comment by sparkiegeek** [comment]
Fixed in #88
