### ISSUE TITLE
Google script is timing out

### ISSUE THREAD

**Issue by tbille** [canonical/specs-v1.canonical.com#96]
The time to parse all the specs is taking too much time on Google script. It seems it might be time to create a cron job that can do this, so we don't rely on Google Script any more.

Google scripts allows the users to run scripts of maximum 30 minutes. The current time to parse the specs reached it!

https://script.google.com/home/projects/1rz8HF3xvERVGFUaOQfu9jpsf_uyB5xNf2jM5gjF3YWwgZgbgqiCFJD27/edit

**Comment by anthonydillon** [comment]
@andesol now that we use a Python script is this resolved?

**Comment by andesol** [comment]
@anthonydillon Yes, we can close it
